### ISSUE TITLE
How to load multiple languages at once?

### ISSUE THREAD

**Issue by RomainGoncalves** [ratson/react-intl-redux#40]
Hi,

thanks for this package. It works great. Just one caveat that I'd like to address.

How could I load all my languages at once (init), save them in redux, and then when changing locale using `updateIntl` having the proper messages being used.
In redux `intl.messages` could be an object looking like so:

```
{
    en: [...en],
    fr: [...fr],
    de: [...de]
}
```

Also I'd like to understand the use of `defaultLocale` during initialization if you can't load multiple languages at once? If I init like this:

```
const messages = {
  fr: frenchMessages,
  en: englishMessages,
  de: deutschMessages,
};

const initialState = {
  intl: {
    defaultLocale: 'en',
    locale: localStorage.locale,
    messages: messages[localStorage.locale],
  },
};
```

Then `defaultLocale` is useless as I can't load the proper messages for that default locale.

I hope I'm clear

Thanks for any help

**Comment by ratson** [comment]
@RomainGoncalves Thanks for the suggestion. However, instead of changing the `intlReducer`, you could manage other language locales in different reducer(s), dispatch `updateIntl` when you need them.

I have added [a new example](https://github.com/ratson/react-intl-redux/tree/master/examples/multiple-languages) about how this could be done, feel free to comment.

I am closing this as there is a solution.
